
project_id = "czljqsxnuylmmfrscski"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false
port = 54324

[storage]
enabled = true

[functions.generate-voice]
verify_jwt = false

[functions.validate-api-key]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
