// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czljqsxnuylmmfrscski.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bGpxc3hudXlsbW1mcnNjc2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjE0NDQsImV4cCI6MjA1NzAzNzQ0NH0.SVVOQL6xXOuWD5wkyUksiQuiUJA-Rxle3m-1-4CbZRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);